# Generated by Django 3.2 on 2021-05-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrarium', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humidité',
            old_name='value',
            new_name='valeur',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='value',
            new_name='valeur',
        ),
        migrations.AddField(
            model_name='temperature',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
